add_newline = true

[custom.direnv]
format = "[\\[direnv\\]]($style) "
style = "fg:yellow"
when = "env | grep -E '^DIRENV_DIR='"

[time]
disabled = false
format = "[$time]($style) "

[git_status]
format = '([\[$conflicted$ahead_behind\]]($style) )'

[package]
symbol = " "
disabled = true

[aws]
symbol = "  "

[gcloud]
symbol = ' '
format = ' [$symbol$active]($style) '

[git_branch]
symbol = " "
style = "bold purple"

[directory]
read_only = " "

[elixir]
symbol = " "

[golang]
symbol = " "

[java]
symbol = " "

[nodejs]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[rust]
symbol = " "
